<a href="https://colab.research.google.com/github/Pratik1joshi/FoundationAI/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import random

# set random seed for reproductivity
np.random.seed(42)

#generate data
num_rows = 100
data={
    'User ID' : range(1, num_rows + 1),
    "Gender": [random.choice(['Male', 'Female']) for _ in range(num_rows)],
    'Age' : [random.randint(18 , 65) for _ in range(num_rows)],
    'Estimated Salary' : np.random.randint(20000, 200000, num_rows),
    'Purchased' : np.random.randint(0, 2, num_rows)
}

#Create dataframe
df = pd.DataFrame(data)
display(df)

User ID  Gender  Age  Estimated Salary  Purchased
0         1  Female   53            141958          0
1         2    Male   29            166867          0
2         3    Male   41            151932          1
3         4    Male   25            123694          0
4         5  Female   65            139879          1
..      ...     ...  ...               ...        ...
95       96  Female   25             59504          0
96       97    Male   48            184231          0
97       98  Female   45             33986          1
98       99    Male   51             81858          0
99      100    Male   24            149312          1

[100 rows x 5 columns]

In [ ]:
df.to_csv('Social_Network_Ads.csv', index=False)

In [ ]:
# import the dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Social_Network_Ads.csv')
df.head(5)

User ID  Gender  Age  Estimated Salary  Purchased
0        1  Female   53            141958          0
1        2    Male   29            166867          0
2        3    Male   41            151932          1
3        4    Male   25            123694          0
4        5  Female   65            139879          1

###Steps:
- Data Preprocessing
- Fitting KNN to the traning set
- Predicting the result
- Test accuracy of the result
- visualise the result


In [ ]:
#Importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Social_Network_Ads.csv')
dataset

User ID  Gender  Age  Estimated Salary  Purchased
0         1  Female   53            141958          0
1         2    Male   29            166867          0
2         3    Male   41            151932          1
3         4    Male   25            123694          0
4         5  Female   65            139879          1
..      ...     ...  ...               ...        ...
95       96  Female   25             59504          0
96       97    Male   48            184231          0
97       98  Female   45             33986          1
98       99    Male   51             81858          0
99      100    Male   24            149312          1

[100 rows x 5 columns]

In [ ]:
x = dataset.iloc[:, [2,3]].values
y = dataset.iloc[:,4].values
display(x)
display(y)

array([[    53, 141958],
       [    29, 166867],
       [    41, 151932],
       [    25, 123694],
       [    65, 139879],
       [    36, 130268],
       [    41,  74886],
       [    27, 157337],
       [    48, 188266],
       [    18, 107498],
       [    25, 132727],
       [    35, 146324],
       [    28, 195203],
       [    19,  36023],
       [    26,  61090],
       [    60,  87221],
       [    51,  84820],
       [    63,  20769],
       [    47,  79735],
       [    58,  84925],
       [    28,  25311],
       [    54, 123355],
       [    31, 105305],
       [    65, 179765],
       [    30, 150608],
       [    64, 176730],
       [    64, 104478],
       [    54, 142537],
       [    40, 169503],
       [    50, 150523],
       [    35,  22747],
       [    56, 143855],
       [    38,  85725],
       [    55, 149981],
       [    60, 104654],
       [    49, 186845],
       [    29, 139346],
       [    44,  87435],
       [    23,  76886],
       [    22,  86803],


array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1])

In [ ]:
import scipy as sk

b = sk.stats.mode(x[0])
b

ModeResult(mode=53, count=1)

In [ ]:
a = x[1].mean()
a

83448.0

In [ ]:
# Splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state=0)

In [ ]:
# feature scaling
from sklearn.preprocessing import StandardScaler
st_x = StandardScaler()
x_train = st_x.fit_transform(x_train)
x_test = st_x.transform(x_test)

In [ ]:
x_test

array([[ 1.4841737 ,  0.01977194],
       [ 0.8646925 ,  0.58579442],
       [-0.09894491,  0.90700293],
       [ 0.10754882,  0.76539448],
       [ 1.14001748, -0.52031828],
       [-1.33790731,  1.79191553],
       [ 0.58936753, -0.34776687],
       [-0.8560886 ,  0.14894712],
       [-1.33790731,  1.32997731],
       [-1.20024482, -0.82109134],
       [-0.99375109,  0.68716768],
       [-0.78725736,  0.76571232],
       [-1.40673855, -0.01163843],
       [-1.61323228, -1.26010745],
       [-1.06258233,  1.00805834],
       [-0.51193238, -1.50832422],
       [-0.78725736,  0.03523408],
       [-0.8560886 ,  0.88224856],
       [ 0.8646925 ,  0.87052576],
       [ 0.3828738 ,  1.58632713]])

Fitting K-NN classifier to the the Training data: Now we will fit the K-NN classifier to the training data. To do this we will import the KNeighborsClassifier class of the Sklearn Neigh

In [ ]:
#Fitting KNN classifier to the training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, metric = 'minkowski', p = 2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0])