<a href="https://colab.research.google.com/github/Pratik1joshi/FoundationAI/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [9]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5,  6,  7])

In [11]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [14]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
n[0,2]=20
n

array([[ 1,  2, 20],
       [ 4,  5,  6],
       [ 7,  8,  9]])

### Randomly generated arrays
Numpy can create arrays filled with random numbers. To ensure reproducibility, you can set a seed using np.random.seed()

In [23]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

### Element wise operation.

In [24]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [25]:
b = (10+(a*2))
b

array([10, 12, 14, 16, 18])

In [27]:
a >= 3

array([False, False, False,  True,  True])

In [28]:
a.std()

1.4142135623730951

In [30]:
a.min()

0

In [31]:
a.max()

4

In [32]:
a.sum()

10